version: '3.4'

services:
  walden_api:
    build: .
    container_name: walden_api
    ports:
      - "9000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - WEAVIATE_URL=http://host.docker.internal:8089
    volumes:
      - ./.env:/app/.env
    restart: unless-stopped
    
  web:
    image: nginx:alpine
    container_name: walden_web
    ports:
      - "3000:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - walden_api
    restart: unless-stopped
